# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 321
# crop_size: 128

data_root: /root/data/VOC2012

# arguments for training
epochs: 80
# batch_size: 2 # per GPU x 4 GPUs
batch_size: 8 # per GPU x 4 GPUs

lr: 0.001
lr_multi: 10.0
criterion:
  name: FocalLoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet50
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
